# Generated by Django 6.0.1 on 2026-04-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Admin'), ('comum', 'Comum')], default='comum', max_length=20),
        ),
    ]
